services:
    postgres:
        image: postgres
        container_name: studies-postgres
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
            interval: 5s
            start_period: 10s
            retries: 5
            timeout: 5s
        ports:
            - 5432:5432

    backend:
        container_name: studies-backend
        restart: on-failure
        build:
            context: .
            dockerfile: backend.Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 8080:8080
